{{- if .Values.cert.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: server
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "common.names.fullname" . }}-tls
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
  duration: 4460h
  dnsNames:
    - {{ include "common.names.fullname" . }}.{{ include "common.names.namespace" . }}.svc.cluster.local
    - {{ include "common.names.fullname" . }}.{{ include "common.names.namespace" . }}.svc
  {{- with .Values.cert.issuer }}
  issuerRef:
    name: {{ .name }}
    kind: {{ .kind }}
    group: cert-manager.io
  {{- end }}
{{- end }}
