{{- if .Values.adminSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kanidm.adminSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if or .Values.adminSecret.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.adminSecret.annotations .Values.commonAnnotations) "context" .) }}
    {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  idm_admin: {{ include "common.secrets.lookup" (dict "secret" (include "kanidm.adminSecretName" .) "key" "idm_admin" "defaultValue" "" "context" $) | quote }}
  system_admin: {{ include "common.secrets.lookup" (dict "secret" (include "kanidm.adminSecretName" .) "key" "system_admin" "defaultValue" "" "context" $) | quote }}
{{- end }}
{{- range $client, $spec := .Values.oauth2 }}
{{- with $spec.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if or .annotations $.Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .annotations $.Values.commonAnnotations) "context" $) }}
    {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- .key | quote | nindent 2 }}: {{ include "common.secrets.lookup" (dict "secret" .name "key" .key "defaultValue" "" "context" $) | quote }}
{{- end }}
{{- end }}
